<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'code' => '192 evoK1C 3030 N',
                'name' => 'Cilindre 30x30 Niquel Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació',
                'price' => 26.50,
                'stock' => 2,
                'discount_percentage' => 15,
                'discount_starts_at' => now()->subHour(),
                'discount_ends_at' => now()->addMinutes(5), // <-- caduca en 5 min
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '30 mm',
                'status' => true,
            ],
            [
                'code' => '192 evoK1C 3030 L',
                'name' => 'Cilindre 30x30 Llautó Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació',
                'price' => 26.50,
                'stock' => 2,
                'discount_percentage' => 20,
                'discount_starts_at' => now()->subDays(2),
                'discount_ends_at' => now()->addDays(7), // actiu una setmana
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '30 mm',
                'status' => true,
            ],
            [
                'code' => '192 evoK1D 3030 N',
                'name' => 'Cilindre 30x30 Niquel Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i doble embrague',
                'price' => 42.00,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '30 mm',
                'status' => true,
            ],
            [
                'code' => '192 evoK1D 3030 L',
                'name' => 'Cilindre 30x30 Llautó Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i Doble embrague',
                'price' => 42.00,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '30 mm',
                'status' => true,
            ],
            [
                'code' => '192 evoK1C 3040 N',
                'name' => 'Cilindre 30x40 Niquel Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació',
                'price' => 30.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '40 mm',
                'status' => true,
            ],
            [
                'code' => '192 evoK1C 3040 L',
                'name' => 'Cilindre 30x40 Llautó Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació',
                'price' => 30.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '40 mm',
                'status' => true,
            ],
            [
                'code' => '192 evoK1D 3040 N',
                'name' => 'Cilindre 30x40 Niquel Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i doble embrague',
                'price' => 47.00,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '40 mm',
                'status' => true,
            ],
            [
                'code' => '192 evoK1D 3040 L',
                'name' => 'Cilindre 30x40 Llautó Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i Doble embrague',
                'price' => 47.00,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '40 mm',
                'status' => true,
            ],
            [
                'code' => 'CIL-001',
                'name' => 'Cilindre 32x32 mm Niquel M&C',
                'description' => '',
                'price' => 85.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '32 mm',
                'ext_size' => '32 mm',
                'status' => true,
            ],
            [
                'code' => 'CIL-002',
                'name' => 'Cilindre 32x32 mm Llautó M&C',
                'description' => '',
                'price' => 85.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '32 mm',
                'ext_size' => '32 mm',
                'status' => true,
            ],
            [
                'code' => 'CIL-003',
                'name' => 'Cilindre 30x30 mm Niquel KESO Omega 2 MASTER',
                'description' => '',
                'price' => 181.74,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '30 mm',
                'status' => true,
            ],
            [
                'code' => 'CIL-004',
                'name' => 'Cilindre 30x30 mm Llautó KESO Omega 2 MASTER',
                'description' => '',
                'price' => 181.74,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '30 mm',
                'ext_size' => '30 mm',
                'status' => true,
            ],
            [
                'code' => 'ESC-001',
                'name' => 'Escut ABUS Plata',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-002',
                'name' => 'Escut ABUS Daurat',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-003',
                'name' => 'Escut DMC Plata',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-004',
                'name' => 'Escut DMC Daurat',
                'description' => '',
                'price' => 0.00,
                'stock' => 3,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-005',
                'name' => 'Escut DMC Boxer Plata',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-006',
                'name' => 'Escut DMC Boxer Daurat',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-007',
                'name' => 'Escut Disec BD180 Plata',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-008',
                'name' => 'Escut Disec BD180 Daurat',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-009',
                'name' => 'Escut Disec BD280 Plata',
                'description' => '',
                'price' => 113.50,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-010',
                'name' => 'Escut Disec BD280 Daurat',
                'description' => '',
                'price' => 113.50,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-011',
                'name' => 'Escut Disec LG280 Plata',
                'description' => '',
                'price' => 130.44,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-012',
                'name' => 'Escut Disec LG280 Daurat',
                'description' => '',
                'price' => 130.44,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-013',
                'name' => 'Escut Disec MG210 Plata',
                'description' => '',
                'price' => 199.53,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-014',
                'name' => 'Escut Disec MG210 Daurat',
                'description' => '',
                'price' => 199.53,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-015',
                'name' => 'Escut Disec MRM 29 Plata',
                'description' => '',
                'price' => 201.22,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'ESC-016',
                'name' => 'Escut Disec MRM 29 Daurat',
                'description' => '',
                'price' => 201.22,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 2,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'SEG-001',
                'name' => 'OFERTA segon pany M&C EZC',
                'description' => 'Pany Ezcurra amb cilindre M&C',
                'price' => 150.00,
                'stock' => 1,
                'discount_percentage' => 10,
                'discount_starts_at' => now()->subDays(1),
                'discount_ends_at' => now()->addDays(3), // actiu 3 dies
                'highlighted' => true,
                'category_id' => 3,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'SEG-002',
                'name' => 'Segon Pany SAG-M&C',
                'description' => 'Pany Sag amb cilindre M&C',
                'price' => 0.00,
                'stock' => 1,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 3,
                'product_type' => 'simple',
                'int_size' => '-',
                'ext_size' => '-',
                'status' => true,
            ],
            [
                'code' => 'pack 001',
                'name' => 'Super pack de cilindres',
                'description' => 'Pack de prova',
                'price' => 26.50,
                'stock' => 2,
                'discount_percentage' => null,
                'discount_starts_at' => null,
                'discount_ends_at' => null,
                'highlighted' => false,
                'category_id' => 1,
                'product_type' => 'pack',
                'int_size' => '',
                'ext_size' => '',
                'status' => true,
            ],
        ]);
    }
}